### ISSUE TITLE
Issues & Questions

### ISSUE THREAD

**Issue by kb0iaa** [shihjay2/nosh3#3]
Doctor,

Love your work, I have been able to log into your demo at: https://demo.noshchartingsystem.com and appreciate your drive for how easy clinical administration and documentation should be for providers. I have struggled trying to get any version working, including Nosh2, Docker-Nosh and now Nosh3. Nosh 3 is by far the easiest to install, however, I am unable to log in via Magic for some reason. It would be easiest for me to install online as local network administration is not a strength of mine. I have attempted to install and run on Vultr (preferably) and even a Droplet instance. Whenever I try to log in to NOSH v3, I get an error message stating "Unauthorized access!". I am wondering if SSL (port 443) access is REQUIRED for successful Magic log in for NOSH v3?

I know how to obtain HTTPS access using NGINX and LetsEncrypt, however, it seems either impossible or extremely difficult to implement NGINX with NOSH v3 due to NOSH's use of both 80 and 443. Is there an easy solution to implement HTTPS that I am unaware of so that this web-based setup will work? In my case, it would also be ideal to run my office website (WordPress) and the NOSH v3 system on the same domain but I'm also not sure if this is actually possible either. Would be ideal for patients to be able to log in to the patient portal and not have to go to a separate website.

I don't know for sure, however, I can't believe that I am the only one having issues like this. I've tried searching for installation videos (i.e. YouTube, etc.) but there is nothing available that walks a regular provider through an installation. Your NOSH project is a great idea, though some of us are having some trouble implementing it. Any guidance you can offer would be amazing. Thank you!

**Comment by shihjay2** [comment]
Thanks for your inquiry - you uncovered some missing instructions in my readme which would result in the Unauthorized access.  This has been fixed in commit [f5e82a0](https://github.com/shihjay2/nosh3/commit/f5e82a0a39ee31804a704bf4579e30b479b8c948).  For your installation, add these 2 lines in your .env file: 
```
NOSH_DISPLAY="My Name"
NOSH_EMAIL=my@email.address
```
Where these entries are your admin/provider address and any subsequent users you add will need to use the email address that is registered to successfully authenticate to NOSH using Magic.
And then restart your Docker instance in your droplet at the root of your docker-compose.yml file
```
docker compose down;docker compose up -d
```

**Comment by kb0iaa** [comment]
Thank you for your input, I did make the changes to the .env file. Tried again using a VPS on VULTR and this change still did not work getting the "Unauthorized access!" message. As a result, spun up a new instance at Digital Ocean and again, made sure that the .env file also had the NOSH_DISPLAY and NOSH_EMAIL lines added this time too. This also, however, did not work and still gives me the "Unauthorized access!" message. My .env file (certain data changed for illustration purposes):

`COUCHDB_URL=http://couchdb:5984`
`COUCHDB_USER=admin`
`COUCHDB_PASSWORD=mypass0528`
`COUCHDB_ENCRYPT_PIN=7140`
`INSTANCE=digitalocean`
`#either [docker, digitalocean, local]`
`NOSH_ROLE=provider`
`AUTH=magic`
`MAGIC_API_KEY=pk_live_00FB00B0000E0EAD`
`#USPSTF_KEY=my_uspstf_key`
`#UMLS_KEY=my_umls_key`
`NOSH_DISPLAY="MY NAME"`
`NOSH_EMAIL=me@mydomain.com`

I have been setting these instances up using Docker 20.10.21 on Ubuntu 22.04, a Ubuntu instance with Docker pre-loaded each time. In the case with Digital Ocean, if I follow the directions and type in `docker-compose up -d` I get a message saying that docker-compose is not installed. If I run the command as 'docker compose up -d` (WITHOUT THE "-") it will set up and run the containers fine apparently. Maybe I should install docker-compose and check that out instead too.

Other things running through my mind is:

-  SSL Certificate - is one required??? I started to purchase one last night but it is more complex to set up to me since I am unable to concurrently install NGINX (or even Apache) at the same time (might be possible but I am no wizard who knows exactly how to make that work properly especially due to the ports). Still trying to figure this out just through Ubuntu. Does Magic require HTTPS???

- I have placed the nosh directory at the same level as the etc, var, dev and root directories (i.e. /nosh). Maybe this needs to go somewhere else? Doesn't seem like it would need to as I can pull up the log in page in a browser without any problems.

- Are certain versions of Ubuntu, Docker or Docker-Compose not compatible?

- Are there any dependencies that Magic has, such as php (7.4, 8.0, etc.) that I don't know about?

- Does Magic or another NOSH component have a port that I have not explicitly opened?

Thanks, I have finally contacted you because I have been struggling for a long time with other versions of NOSH, never being able to get an online instance running. Like I mentioned before, I can't be the only one having issues trying to get this to work. Most others, however, probably gave up already. With more users, there would be better support and referrals I would think. Have you tried setting up an online instance of these lately? I wish I could essentially see what you are doing so I could get this to work.

Thanks again for any continued help. I would love to be able to recommend this to other providers too.

**Comment by shihjay2** [comment]
Docker did update the docker compose command since the time the readme was first generated ~1 year ago so I will need to update to `docker compose up -d` instead of `docker-compose up -d`.

Magic does NOT require HTTPS (I can do my own testing using http://localhost without any problems).  Just confirming you are entering the same e-mail address that is placed in the .env file and, just to be sure, clear out all local storage on the browser (if on Chrome, go to Developer Tools -> Application -> Storage and Clear site data) and try again.  If you get the point of getting the Magic authentication, clearly you do not need HTTPS/SSL to work on the device.

However, if you plan on using NOSH3 for patient and online access from anywhere, it is essential that you host it on a public server that has HTTPS set for security.

If you're using Docker Compose, it automatically has a router configured (Traefik container) that pushes all valid endpoints to NOSH automatically.  You do NOT need to use Apache or NGNIX; you just only need to open ports 80 and 443 (SSL) on the droplet and that's it.  Of course, if you plan on hosting other services in other ports or need to use 80/443 for those other services, then you'll need to reconfigure Traefik in the docker-compose.yml file which is outside the scope of this project (but can be done if you review the Traefik documentation).

All versions of Ubuntu/Docker/Docker-Compose should be compatible as defined by the dependencies for the version of Ubuntu/Docker you're using; should not matter for NOSH.

There are no dependencies for Magic (it's an RESTful API so it's just HTTP commands) and it's all coded in the project so there's nothing you need to do differently.  You do not need to do any additional configuration for Magic (no whitelist/blacklist) since it's not redirecting back from an email link to the tab that you should have left open when you initiated the login.  You just need to use the correct API key you created when you set up the Magic account and ports 80/443 open on your server.

NOSH3 doesn't use any PHP code whatsoever - it's all JS and it's a complete departure from all versions of NOSH previously (that's why you don't need Apache).

**Comment by shihjay2** [comment]
BTW purchasing SSL certificate IS NOT needed.  Traefik automatically generates a Let'sEncrypt SSL certificate (no fee) based on the domain name you registered for your server that is pointed to the IP address of your droplet.  You can get a reasonably priced domain name through NameCheap.

**Comment by kb0iaa** [comment]
I already have a domain name pointed to the droplet. When loading the NOSH login page, however, I and type in the domain name in the browser it brings it up as http (unsecure). I might have to try and do this locally to make things work, I guess. Not looking forward to that but since I am unable to get the online version up and running successfully, seems like that is my only choice at this time.

**Comment by shihjay2** [comment]
After further review, I identified further errors in my instructions.  Pardon, as I have been mostly testing NOSH 3 (it's not "officially released" yet) for the patient health record deployment which uses  different environment variables and uses DigitalOcean App Platform for deployment so I didn't do extensive testing for provider/clinic NOSH.  I have figured out the problem - no Let's Encrypt directive in the Traefik calls in docker-compose.yml.  I have updated the readme in commit 657b247ac0454483a513f20921a7437a41bcad2b.

**Comment by kb0iaa** [comment]
Now it all makes sense, I thought it was officially released already - thank you for the clarification. I know you must be busy, trying to get everything done with work, your family and this project. I will be patient and actually wait for your official release. Thanks again!
