### ISSUE TITLE
Config for Installation to subdomain

### ISSUE THREAD

**Issue by christian-geier** [shihjay2/nosh3#7]
Hi, great project! I am trying to install nosh3 on a Ubuntu VPS that also hosts a practice website "example.com".

Is it possible to install it to a subdomain, e.g. emr.example.com ? If so, how do I need to set the A record and config files ?

Thanks!! Christian

**Comment by shihjay2** [comment]
Your domain needs to either have a wildcard (or specific subdomain) set as a CNAME (routing to the same domain/IP as your Ubuntu VPS that hosts the practice website).  Traefik is a reverse proxy router that is already a part of the docker-compose.yml directives in this project.  Look into using [Traefik Documentation](https://doc.traefik.io/traefik/) for ways to incorporate your practice website.  Depending on how your practice website is configured, you will likely need to reassign the website port (assuming your website is on port 80 and 443) as that will conflict with Traefik (Traefik should always start with port 80 and 443 since it's the root router).  Once you re-assign it, you can then create a [Traefik file config](https://doc.traefik.io/traefik/providers/file/) that provides directives to route the base domain to you practice website and you'll need to make changes to docker-compose.yml for the nosh3 service to the subdomain that you want to use.  Hope that helps.

**Comment by christian-geier** [comment]
Thanks for the detailed reply! Did not know about Traefik. I'll try if I can set up Nosh3 on a separate server first, and once that works I have a better sense now how it can all work on a single server.
